"""add payment_allocations table and integrity triggers

Revision ID: cdcfc75c5dab
Revises: eb96bc5d4029
Create Date: 2026-05-19 05:57:59.090302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdcfc75c5dab'
down_revision: Union[str, None] = 'eb96bc5d4029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('charge_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['charge_id'], ['charges.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Тригер: user_community_roles.unit_id має належати тій самій community
    op.execute("""
        CREATE OR REPLACE FUNCTION check_ucr_unit_community()
        RETURNS TRIGGER AS $$
        BEGIN
            IF NEW.unit_id IS NOT NULL THEN
                IF NOT EXISTS (
                    SELECT 1 FROM units
                    WHERE id = NEW.unit_id AND community_id = NEW.community_id
                ) THEN
                    RAISE EXCEPTION 'unit_id % does not belong to community_id %',
                        NEW.unit_id, NEW.community_id;
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER trg_check_ucr_unit_community
        BEFORE INSERT OR UPDATE ON user_community_roles
        FOR EACH ROW EXECUTE FUNCTION check_ucr_unit_community();
    """)

    # Тригер: charges.charge_type_id має належати тій самій community що й unit_id
    op.execute("""
        CREATE OR REPLACE FUNCTION check_charge_community()
        RETURNS TRIGGER AS $$
        DECLARE
            v_unit_community_id INTEGER;
            v_ct_community_id INTEGER;
        BEGIN
            SELECT community_id INTO v_unit_community_id
            FROM units WHERE id = NEW.unit_id;

            SELECT community_id INTO v_ct_community_id
            FROM charge_types WHERE id = NEW.charge_type_id;

            IF v_unit_community_id != v_ct_community_id THEN
                RAISE EXCEPTION 'charge_type (community %) does not match unit (community %)',
                    v_ct_community_id, v_unit_community_id;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER trg_check_charge_community
        BEFORE INSERT OR UPDATE ON charges
        FOR EACH ROW EXECUTE FUNCTION check_charge_community();
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_check_charge_community ON charges;")
    op.execute("DROP FUNCTION IF EXISTS check_charge_community();")
    op.execute("DROP TRIGGER IF EXISTS trg_check_ucr_unit_community ON user_community_roles;")
    op.execute("DROP FUNCTION IF EXISTS check_ucr_unit_community();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_allocations')
    # ### end Alembic commands ###
